# -*- coding: utf8 -*-

from certbot_adc import CadcProviderBase
from QcloudApi.qcloudapi import QcloudApi


class CadcProviderQcloud(CadcProviderBase):
    api: QcloudApi

    def __init__(self, qcloud_api: QcloudApi): ...

    def update_txt_record(self, main_domain: str, record_id: int, sub_domain: str, value: str) -> None: ...

    def add_txt_record(self, main_domain: str, sub_domain: str, value: str) -> None: ...

    def get_txt_record(self, main_domain: str, sub_domain: str) -> tuple: ...

    def delete_txt_record(self, main_domain: str, record_id: int) -> None: ...

    def owns_domain(self, domain: str): ...

    def update_dns01(self, domain: str, token: str) -> None: ...

    def clean_dns01(self, domain: str) -> None: ...
