# -*- coding: utf8 -*-

class CadcConf:
    domain_mappings: dict
    name_mappings: dict
    confFile: str
    confDict: str

    def __init__(self, conf_file: str = None): ...

    def find_conf_file(self) -> str: ...

    def check_provider_aliyun(self, name: str, provider: dict) -> None: ...

    def check_provider_qcloud(self, name: str, provider: dict) -> None: ...

    def map_by_domain(self) -> None: ...

    def find_provider_by_domain(self, domain: str) -> dict: ...

    def check(self) -> None: ...
