# -*- coding: utf8 -*-

from certbot_adc import CadcProviderBase
from aliyunsdkcore.client import AcsClient


class CadcProviderAliyun(CadcProviderBase):
    acs_client: AcsClient

    def __init__(self, acs_client: AcsClient): ...

    def get_owned_domain_info(self, main_domain: str) -> dict: ...

    def owns_domain(self, full_domain: str) -> tuple: ...

    def get_txt_record(self, recordId: str) -> dict: ...

    def update_txt_record(self, recordId: str, rr: str, value: str) -> str: ...

    def delete_txt_record(self, record_id: str) -> None: ...

    def add_txt_record(self, domain: str, rr: str, value: str) -> str: ...

    def find_target_txt_record(self, domain: str, rr: str) -> str: ...

    def update_dns01(self, domain: str, token: str) -> None: ...

    def clean_dns01(self, domain: str) -> None: ...
