version: "2.1"
services:
  leanote:
#    image: nykma/leanote:latest
    build:
       context: .
       dockerfile: leanote/Dockerfile
    volumes:
      - "./conf/app.conf:/go/src/github.com/leanote/leanote/conf/app.conf"
      - './data/leanote/log:/var/log'
    ports:
      - "9000:9000"
    depends_on:
      - mongo

  mongo:
#    image: nykma/leanote-mongodb:latest
    build:
       context: .
       dockerfile: mongo/Dockerfile
    entrypoint: "/bin/bash"
    command:
      - "/root/start-db.sh"
    healthcheck:
      test: "echo 'db.stats().ok' | mongo 127.0.0.1:27017/leanote --quiet"
    volumes:
      - "./data/mongodb:/data/db"
